// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LXxkOjzBUryx_lFPWBHlZwAzYPVadTM',
    appId: '1:438827042202:web:2ced64c0cb418c0fe52623',
    messagingSenderId: '438827042202',
    projectId: 'quanlygiaotrinh',
    authDomain: 'quanlygiaotrinh.firebaseapp.com',
    storageBucket: 'quanlygiaotrinh.firebasestorage.app',
    measurementId: 'G-T48C065BQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfh1IJNz8CgfMYVjEG_CAA73SmhZFpH4c',
    appId: '1:438827042202:android:ba03f5eca88d1d5be52623',
    messagingSenderId: '438827042202',
    projectId: 'quanlygiaotrinh',
    storageBucket: 'quanlygiaotrinh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMf8qEo8iD2qn7k3qbkdMOE_kpEOwvVo',
    appId: '1:438827042202:ios:4a7f92221f765312e52623',
    messagingSenderId: '438827042202',
    projectId: 'quanlygiaotrinh',
    storageBucket: 'quanlygiaotrinh.firebasestorage.app',
    iosBundleId: 'com.example.quanLyGiaoTrinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMf8qEo8iD2qn7k3qbkdMOE_kpEOwvVo',
    appId: '1:438827042202:ios:4a7f92221f765312e52623',
    messagingSenderId: '438827042202',
    projectId: 'quanlygiaotrinh',
    storageBucket: 'quanlygiaotrinh.firebasestorage.app',
    iosBundleId: 'com.example.quanLyGiaoTrinh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8LXxkOjzBUryx_lFPWBHlZwAzYPVadTM',
    appId: '1:438827042202:web:2e1650ba562b5039e52623',
    messagingSenderId: '438827042202',
    projectId: 'quanlygiaotrinh',
    authDomain: 'quanlygiaotrinh.firebaseapp.com',
    storageBucket: 'quanlygiaotrinh.firebasestorage.app',
    measurementId: 'G-FRR64WYEQX',
  );
}
